#!/bin/sh

# 解决已联网的问题
cp distfeeds.conf /etc/opkg/distfeeds.conf

# 恢复已安装列表
opkg update
cat packages-list.txt | cut -f 1 -d ' ' | xargs opkg install

# 恢复/overlay 配置
tar -xzvf overlay_backup.tar.gz -C /
reboot
